### ISSUE TITLE
Clients in the wild (especially mobile) often don't respect DNS TTL

### ISSUE THREAD

**Issue by jstauter-mdsol** [aws-samples/ecs-canary-blue-green-deployment#2]
I think this should come with a warning. This system is very similar to one I developed recently that had to be completely reimplemented because in practice, clients can't be trusted to refresh their DNS when you'd like them to. Not suitable for production use unless you also control the client DNS.

**Comment by nbrandaleone** [comment]
Hi Joshua,

I will consider adding a sentence regarding this as a concern.  It is out of our control, but it probably should be mentioned.

	Nick

**Comment by nbrandaleone** [comment]
I have added a warning to the README, since I have found your comment and concern to be valid.
